### ISSUE TITLE
Outdated freemarker version

### ISSUE THREAD

**Issue by Paratron** [kaola-fed/freemarker#6]
Hey,
the version of freemarker used by this module is outdated. Current version on freemarker.apache.org is 2.3.28, the version of this module is 2.3.21.

This may appear as not that big of a difference, but for example [loop variable builtins](https://freemarker.apache.org/docs/ref_builtins_loop_var.html) have been introduced with 2.3.23.

Is there a way to update the freemarker version used?

**Comment by Paratron** [comment]
my pull request #7 will fix this

**Comment by davizp** [comment]
Any update on this? I have fixed the "npm test" issue, it was a syntax error.

https://github.com/kaola-fed/freemarker/pull/8

**Comment by int64ago** [comment]
Released via `v2.0.0`
